---
  apiVersion: v1
  kind: Service
  name: jenkins
    labels:
      run: jenkins
      tier: frontend

  spec: 
    type: LoadBalancer
    selector: 
      run: jenkins

    ports:
      - 
        name: http
        port: 80
        targetPort: 8080
        protocol: TCP

      - 
        name: slave
        port: 50000
        protocol: TCP
